//! Third-party licences: what finstats is built on, and the licence each part is under.

use std::sync::OnceLock;

use axum::http::HeaderValue;
use axum::http::header::CONTENT_TYPE;
use axum::response::IntoResponse;
use serde::{Deserialize, Serialize};

use crate::auth::AuthUser;

const SOURCE: &str = include_str!("../THIRD-PARTY.json");

/// What is inside the binary but is not a crate, so nothing generated can know about it:
/// finstats itself, the two fonts, the map — and the city database, which is not shipped at
/// all but is read by whoever switches it on, and asks to be credited.
/// Each licence file that really exists on disk is compiled in; nothing here is retyped.
const BUNDLED: &[(&str, &str, &str, &str, Option<&str>)] = &[
    ("finstats", env!("CARGO_PKG_VERSION"), "GPL-3.0-only", "https://github.com/OlaYZen/finstats", Some(include_str!("../LICENSE"))),
    ("Inter", "", "OFL-1.1", "https://github.com/rsms/inter", Some(include_str!("../web/assets/fonts/LICENSE-Inter.txt"))),
    ("Inter (cards)", "4.1", "OFL-1.1", "https://github.com/rsms/inter", Some(include_str!("../fonts/card/LICENSE-Inter.txt"))),
    ("JetBrains Mono", "", "OFL-1.1", "https://github.com/JetBrains/JetBrainsMono", Some(include_str!("../web/assets/fonts/LICENSE-JetBrainsMono.txt"))),
    ("Natural Earth", "1:50m", "Public domain", "https://www.naturalearthdata.com", None),
    ("DB-IP IP to City Lite", "", "CC-BY-4.0", "https://db-ip.com/db/lite.php", None),
];

fn crate_kind() -> String {
    "crate".into()
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
pub struct Component {
    pub name: String,
    pub version: String,
    /// SPDX expression as the crate itself declares it ("MIT OR Apache-2.0").
    pub license: String,
    pub repository: String,
    /// Which of `Notices::notices` this component ships, by index.
    pub notices: Vec<usize>,
    /// "app", "bundled" or "crate" — the generated file names none, so a crate it is.
    #[serde(default = "crate_kind")]
    pub kind: String,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
pub struct Notice {
    pub file: String,
    pub text: String,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Default)]
pub struct Notices {
    pub components: Vec<Component>,
    pub notices: Vec<Notice>,
}

/// The whole notice: the generated crate list plus what is bundled by hand.
pub fn notice() -> Notices {
    let mut n: Notices = serde_json::from_str(SOURCE).expect("THIRD-PARTY.json is generated by tools/make-third-party.py and must parse");
    let mut head = vec![];
    for &(name, version, license, repository, text) in BUNDLED {
        let notices = match text {
            Some(text) => {
                n.notices.push(Notice { file: format!("{name} licence"), text: text.trim().to_string() });
                vec![n.notices.len() - 1]
            }
            None => vec![],
        };
        let kind = if name == env!("CARGO_PKG_NAME") { "app" } else { "bundled" };
        head.push(Component { name: name.into(), version: version.into(), license: license.into(), repository: repository.into(), notices, kind: kind.into() });
    }
    head.append(&mut n.components);
    n.components = head;
    n
}

/// The answer, rendered once: it is the same for every caller and cannot change while the
/// process runs, and it runs to half a megabyte of licence text.
fn body() -> &'static str {
    static BODY: OnceLock<String> = OnceLock::new();
    BODY.get_or_init(|| {
        let n = notice();
        serde_json::json!({ "version": env!("CARGO_PKG_VERSION"), "components": n.components, "notices": n.notices }).to_string()
    })
}

/// `GET /api/licenses` — finstats' own licence and every third-party one it is built on.
pub async fn licenses(_user: AuthUser) -> impl IntoResponse {
    ([(CONTENT_TYPE, HeaderValue::from_static("application/json"))], body())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn the_notice_lists_a_crate_with_its_licence() {
        let n = notice();
        let serde = n.components.iter().find(|c| c.name == "serde").expect("serde is a dependency and must be in the notice");
        assert!(serde.license.contains("MIT"), "serde's licence expression is missing: {:?}", serde.license);
        assert!(!serde.notices.is_empty(), "serde ships licence texts; the notice must carry them");
    }

    /// The fonts and the map are not crates, so nothing generated can know about them.
    #[test]
    fn the_notice_covers_what_is_bundled_and_finstats_itself() {
        let n = notice();
        let text = |name: &str| {
            let c = n.components.iter().find(|c| c.name == name).unwrap_or_else(|| panic!("{name} is shipped inside the binary and must be in the notice"));
            (c.license.clone(), c.notices.iter().map(|&i| n.notices[i].text.as_str()).collect::<Vec<_>>().join("\n"))
        };
        let (license, body) = text("finstats");
        assert_eq!(license, "GPL-3.0-only");
        assert!(body.contains("GNU GENERAL PUBLIC LICENSE"), "finstats' own licence text belongs here too");
        for font in ["Inter", "JetBrains Mono"] {
            let (license, body) = text(font);
            assert_eq!(license, "OFL-1.1");
            assert!(body.contains("SIL OPEN FONT LICENSE"), "{font} must carry the licence file that sits beside it");
        }
        assert_eq!(text("Natural Earth").0, "Public domain");
    }

    /// The whole notice is the same for everybody and never changes while the process runs,
    /// so it is rendered once and handed out as it stands.
    #[test]
    fn the_answer_is_rendered_once_and_carries_the_running_version() {
        let v: serde_json::Value = serde_json::from_str(body()).expect("the answer must be JSON");
        assert_eq!(v["version"], env!("CARGO_PKG_VERSION"));
        assert_eq!(v["components"].as_array().map(|a| a.len()), Some(notice().components.len()));
        assert!(v["notices"].as_array().is_some_and(|a| a.len() > 50), "the licence texts themselves are the point of it");
        assert!(std::ptr::eq(body(), body()), "it is built once, not per request");
    }

    /// The gate on the generated half: Cargo.lock is the dependency graph as cargo resolved it,
    /// so a crate added, removed or bumped without re-running `tools/make-third-party.py` fails here.
    #[test]
    fn the_notice_covers_every_crate_in_the_lockfile() {
        let n = notice();
        let have: HashSet<(&str, &str)> = n.components.iter().map(|c| (c.name.as_str(), c.version.as_str())).collect();
        for (name, version) in lockfile(include_str!("../Cargo.lock")) {
            if name == env!("CARGO_PKG_NAME") {
                continue;
            }
            assert!(have.contains(&(name, version)), "{name} {version} is a dependency with no licence recorded — run tools/make-third-party.py");
        }
        for c in &n.components {
            assert!(!c.license.is_empty() || !c.notices.is_empty(), "{} is listed with no licence at all", c.name);
            for &i in &c.notices {
                assert!(n.notices.get(i).is_some_and(|t| !t.text.is_empty()), "{} points at licence text {i}, which is not there", c.name);
            }
        }
    }

    /// `[[package]]` blocks, as `name` and `version`.
    fn lockfile(source: &str) -> Vec<(&str, &str)> {
        fn value(line: &str) -> &str {
            line.split_once('"').map(|(_, r)| r.trim_end_matches('"')).unwrap_or("")
        }
        let mut out = vec![];
        let mut name = None;
        for line in source.lines() {
            if let Some(rest) = line.strip_prefix("name = ") {
                name = Some(value(rest));
            } else if let Some(rest) = line.strip_prefix("version = ")
                && let Some(name) = name.take()
            {
                out.push((name, value(rest)));
            }
        }
        out
    }
}
